### ISSUE TITLE
[classloader] goto/jump: parse offset into opcode count

### ISSUE THREAD

**Issue by liketechnik** [cmjava2023/vm#61]
Follow up of #60

**Comment by Kerreytsugo** [comment]
In our List of opcodes we dont differentiate between for example iload and iload_<n>, wich have different amounts of bytes. so we can not just use the parsed list to check size of an opcode

**Comment by Kerreytsugo** [comment]
Proposed Idea: We have a second list with sizes and every time we parse an opcode, we add the size of the opcode to that list, so that we can iterate through that list, to find the needed offset opcodes
