### ISSUE TITLE
Fully qualified names in heap 

### ISSUE THREAD

**Issue by Kerreytsugo** [cmjava2023/vm#81]
How do we want to add the fully qualified names in the heap for classes without packages?

"/Class"
or 
"Class"

**Comment by liketechnik** [comment]
I'd like to have the following, if we want to get the package/class name stuff straight:
```rust
pub type PackageName = Option<String>;
pub type ClassName = String;
pub type ClassIdentifier = (PackageName, ClassName)
```

**Comment by liketechnik** [comment]
And if we do this, I'd like to have this basically everywhere, except at the stage where we read the raw combined class/package name from the .class-file.

**Comment by Kerreytsugo** [comment]
This sounds fine for me.
I would suggest, we refactor this with at least one person from classloader and executor.

**Comment by liketechnik** [comment]
I just now realized: We may want to also abstract the array class names (e.g. `[[I`]) here. Though I am not sure on how that should look then. I came up with the following variant in the end:
```rust
// Variant A
struct ClassIdentifier {
  package: Option<String>,
  class_name: ClassName,
}
enum ClassName {
  Array { dimensions: usize, name: ArrayName, },
  Plain(String),
}
enum ArrayName {
  Class(String),
  Byte, Int, // + all other primitive types
}
```
